DROP TRIGGER BROJ_TELEFONA_AUTO_PK;
DROP SEQUENCE "BROJ_TELEFONA_ID_SEQ";

DROP TRIGGER DRZI_CAS_AUTO_PK;
DROP SEQUENCE "DRZI_CAS_ID_SEQ";

DROP TRIGGER FUNKCIJA_AUTO_PK;
DROP SEQUENCE "FUNKCIJA_ID_SEQ";

DROP TRIGGER GODINA_AUTO_PK;
DROP SEQUENCE "GODINA_ID_SEQ";

DROP TRIGGER IMA_OCENU_AUTO_PK;
DROP SEQUENCE "IMA_OCENU_ID_SEQ";

DROP TRIGGER JE_RAZREDNI_AUTO_PK;
DROP SEQUENCE "JE_RAZREDNI_ID_SEQ";

DROP TRIGGER JE_RODITELJ_AUTO_PK;
DROP SEQUENCE "JE_RODITELJ_ID_SEQ";

DROP TRIGGER KORISNIK_AUTO_PK;
DROP SEQUENCE "KORISNIK_ID_SEQ";

DROP TRIGGER ODELJENJE_AUTO_PK;
DROP SEQUENCE "ODELJENJE_ID_SEQ";

DROP TRIGGER PREDAJE_AUTO_PK;
DROP SEQUENCE "PREDAJE_ID_SEQ";

DROP TRIGGER PREDMET_AUTO_PK;
DROP SEQUENCE "PREDMET_ID_SEQ";

DROP TRIGGER PREDSTAVLJA_AUTO_PK;
DROP SEQUENCE "PREDSTAVLJA_ID_SEQ";

DROP TRIGGER RASPORED_AUTO_PK;
DROP SEQUENCE "RASPORED_ID_SEQ";


DROP TABLE BROJ_TELEFONA;
DROP TABLE DRZI_CAS;
DROP TABLE FUNKCIJA;
DROP TABLE JE_RAZREDNI;
DROP TABLE JE_RODITELJ;
DROP TABLE IMA_OCENU;
DROP TABLE PREDAJE;
DROP TABLE GODINA;
DROP TABLE PREDSTAVLJA;
DROP TABLE RASPORED;
DROP TABLE KORISNIK;
DROP TABLE ODELJENJE;
DROP TABLE PREDMET;
